baseURL: "https://laa-hecap.github.io/webpage/"
theme: "up-business-theme"
languageCode: "en-us"

title: "LAA-HECAP"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Up Business"
  description: "Latin American Association for High Energy, Cosmology and Astroparticle Physics. Our objective is to take advantage of and amplify the successful and growing research dynamics in HECAP in Latin America"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "#"
    instagram: "#"
    facebook: "#"
    twitter: "#"

  location:
    - "3891 Ranchview Dr. Richardson, California 62639"
    - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "trungkienspktnd@gamail.com"
    - "207.555.0119"

  copyright: "© 2022 Up Business All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Newsletter"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Register!"
      url: "https://t.co/4HzoWqXL71"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Pricing"
      url: "/#"
      weight: 4

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
